//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ ���ɵİ����ļ���
// �� MFCApplication1.rc ʹ��
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCAPPLICATION1_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   132
#define IDD_SETTINGS_DIALOG             133
#define IDD_CLICK_SPEED_DIALOG          135
#define IDD_QRCODE_DLG                  136
#define IDD_SCREENSHOT_OCR_DLG          137
#define IDD_BATCH_RENAME_DLG            138
#define IDD_REGEX_GUIDE_DLG             139
#define IDD_FOLDER_PROCESS_DLG          140
#define IDD_INPUT_DLG                   141
#define IDC_TAB1                        1000
#define IDC_LIST1                       1001
#define IDC_LIST2                       1002
#define IDC_COMBO1                      1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON2                     1005
#define IDC_EDIT1                       1006
#define IDC_EDIT2                       1007
#define IDC_EDIT3                       1008
#define IDC_EDIT4                       1009
#define IDC_BUTTON3                     1010
#define IDC_STATIC_PATH                 1011
#define IDC_CHECK1                      1014
#define IDC_CHECK2                      1015
#define IDC_BUTTON4                     1016
#define IDC_BUTTON5                     1017
#define IDC_BUTTON6                     1018
#define IDC_BUTTON7                     1019
#define IDC_BUTTON8                     1020
#define IDC_BUTTON9                     1021
#define IDC_BUTTON10                    1022
#define IDC_BUTTON11                    1023
#define IDC_SLIDER1                     1024
#define IDC_EDIT5                       1025
#define IDC_BUTTON12                    1026
#define IDC_BUTTON13                    1027
#define IDC_BUTTON14                    1028
#define IDC_CHECK3                      1031
#define IDC_EDIT6                       1032
#define IDC_BUTTON17                    1033
#define IDC_BUTTON18                    1034
#define IDC_CHECK4                      1035
#define IDC_LIST3                       1036
#define IDC_BUTTON19                    1037
#define IDC_SPLIT1                      1038
#define IDC_BUTTON20                    1039
#define IDC_BUTTON21                    1040
#define IDC_BUTTON22                    1041
#define IDC_STATIC7                     1042
#define IDC_STATIC13                    1043
#define IDC_EDIT7                       1044
#define IDC_BUTTON23                    1045
#define IDC_EDIT8                       1046
#define IDC_BUTTON24                    1047
#define IDC_BUTTON25                    1048
#define IDC_BUTTON26                    1049
#define IDC_CHECK5                      1050
#define IDC_CHECK6                      1051
#define IDC_MFCEDITBROWSE2              1060
#define IDC_STATIC14                    1061
#define IDC_BUTTON27                    1066
#define IDC_BUTTON28                    1067
#define IDC_BUTTON29                    1068
#define IDC_LIST4                       1069
#define IDC_BUTTON30                    1070
#define IDC_BUTTON31                    1071
#define IDC_BUTTON32                    1075
#define IDC_LIST5                       1076
#define IDC_BUTTON33                    1077
#define IDC_EDIT_DEFAULT_NAME           1078
#define IDC_LIST6                       1178
#define IDC_EDIT_BILI_PATH              1079
#define IDC_LIST7                       1179
#define IDC_BROWSE_BILI                 1080
#define IDC_EDIT_WECHAT_PATH            1081
#define IDC_BROWSE_WECHAT               1082
#define IDC_EDIT_QQ_PATH                1083
#define IDC_BROWSE_QQ                   1084
#define IDC_EDIT_VSCODE_PATH            1085
#define IDC_BROWSE_VSCODE               1086
#define IDC_EDIT_VS_PATH                1087
#define IDC_BROWSE_VS                   1088
#define IDC_EDIT_GITBASH_PATH           1089
#define IDC_BROWSE_GITBASH              1090
#define IDC_EDIT_YUANBAO_PATH           1091
#define IDC_BROWSE_YUANBAO              1092
#define IDC_EDIT_STUDY_PATH             1093
#define IDC_BROWSE_STUDY                1094
#define IDC_EDIT_DOWNLOAD_PATH          1095
#define IDC_BROWSE_DOWNLOAD             1096
#define IDC_EDIT_MOOC_URL               1097
#define IDC_EDIT_SDUCS_URL              1098
#define IDC_SLIDER2                     1099
#define IDC_STATIC18                    1100
#define IDC_BUTTON15                    1101
#define IDC_BUTTON16                    1102
#define IDC_STATIC_IGNORE_GROUP         1102
#define IDC_EDIT_SCREENSHOT_DIR         1103
#define IDC_BROWSE_SCREENSHOT           1104
#define IDC_SLIDER_CLICK_SPEED          1105
#define IDC_EDIT_CLICK_SPEED            1106
#define IDC_EDIT_CLICK_INTERVAL         1107
#define IDC_STATIC_CLICK_STATUS         1109
#define IDC_EDIT_CLICK_KEY_START        1110
#define IDC_EDIT_CLICK_KEY_STOP         1111
#define IDC_STATIC12                    1112
#define IDC_EDIT_QR_TEXT                1112
#define IDC_BTN_QR_GENERATE             1113
#define IDC_STATIC_QR_IMAGE             1114
#define IDC_BTN_QR_COPY                 1115
#define IDC_BTN_QR_SAVE                 1116
#define IDC_BTN_OCR_CAPTURE             1117
#define IDC_EDIT_OCR_RESULT             1118
#define IDC_BTN_OCR_COPY                1119
#define IDC_STATIC_OCR_STATUS           1120
#define IDC_EDIT_RENAME_FOLDER          1121
#define IDC_BTN_RENAME_BROWSE           1122
#define IDC_LIST_RENAME                 1123
#define IDC_EDIT_RENAME_PREFIX          1124
#define IDC_EDIT_RENAME_SUFFIX          1125
#define IDC_EDIT_RENAME_REPLACE_FROM    1126
#define IDC_EDIT_RENAME_REPLACE_TO      1127
#define IDC_CHECK_RENAME_NUMBER         1128
#define IDC_EDIT_RENAME_START_NUM       1129
#define IDC_BTN_RENAME_PREVIEW          1130
#define IDC_BTN_RENAME_EXECUTE          1131
#define IDC_CHECK_RENAME_REGEX          1132
#define IDC_BTN_OCR_TRANSLATE           1133
#define IDC_EDIT_OCR_TRANSLATED         1134
#define IDC_BTN_RENAME_CLEAR            1135
#define IDC_BTN_RENAME_REGEX_HELP       1136
#define IDC_TAB_FOLDER                  1137
#define IDC_LIST_FOLDERS                1138
#define IDC_BTN_FOLDER_RENAME           1139
#define IDC_BTN_FOLDER_MOVE             1140
#define IDC_BTN_FOLDER_DELETE           1141
#define IDC_BTN_FOLDER_SELECTALL        1142
#define IDC_BTN_FOLDER_DESELECTALL      1143
#define IDC_EDIT_FOLDER_DEST            1144
#define IDC_BTN_FOLDER_DEST_BROWSE      1145
#define IDC_BTN_FOLDER_EXECUTE          1146
#define IDC_CHECK_DELETE_MATCH          1147
#define IDC_EDIT_DELETE_PATTERN         1148
#define IDC_STATIC_TAB0_TARGET          1149
#define IDC_STATIC_TAB1_PREFIX          1150
#define IDC_STATIC_TAB1_SUFFIX          1151
#define IDC_STATIC_TAB1_REPLACE_FROM    1152
#define IDC_STATIC_TAB1_REPLACE_TO      1153
#define IDC_STATIC_TAB1_START_NUM       1154
#define IDC_STATIC_TAB1_TIP             1155
#define IDC_BTN_FILE_UNMARK_ALL         1156
#define IDC_CHECK_DELETE_INVERT         1157
#define IDC_CHECK_NUMBER_AFTER_EXT      1158
#define IDC_INPUT_PROMPT                1159
#define IDC_INPUT_EDIT                  1160
#define IDC_BTN_FILE_RESET_ALL          1161
#define IDC_BTN_CURRENT_RENAME          1162
#define IDC_BTN_CURRENT_MOVE            1163
#define IDC_BTN_CURRENT_DELETE          1164
#define IDC_STATIC_CURRENT_DIR          1165
#define IDC_STATIC_SUBDIR               1166
#define IDC_STATIC_FOLDER_SELCOUNT      1167
#define IDC_BTN_RENAME_REFRESH          1168
#define IDC_CHECK_IGNORE_EXT            1169
#define IDC_EDIT_IGNORE_EXT             1170
#define IDC_CHECK_IGNORE_MATCH          1171
#define IDC_EDIT_IGNORE_PATTERN         1172
#define IDC_CHECK_IGNORE_REGEX          1173
#define IDC_BTN_IGNORE_CLEAR            1174
#define IDC_COMBO_OCR_LANG              1175
#define IDC_EDIT_PROCESS_FILTER         1176
#define IDC_CHECK_PROCESS_REGEX         1177
#define IDC_CHECK_TRACK_EXT            1180
#define IDC_EDIT_TRACK_EXT             1181
#define IDC_CHECK_TRACK_MATCH          1182
#define IDC_EDIT_TRACK_PATTERN         1183
#define IDC_CHECK_TRACK_REGEX          1184
#define IDC_BTN_TRACK_CLEAR            1185
#define IDC_STATIC_TRACK_GROUP         1186
#define IDC_BTN_PROCESS_REGEX_HELP     1187

#define ID_FILE_SETTINGS                32775
#define ID_FILE_EXIT                    32776
#define ID_HELP_ABOUT                   32777
#define ID_VIEW_PROCESS                 32778
#define ID_VIEW_STARTUP                 32779
#define ID_VIEW_CLIPBOARD               32780
#define ID_VIEW_WINDOW                  32781
#define ID_VIEW_FILE                    32782
#define ID_VIEW_GIT                     32783
#define ID_TOOLS_WECHAT                 32784
#define ID_TOOLS_QQ                     32785
#define ID_TOOLS_VSCODE                 32786
#define ID_TOOLS_VS                     32787
#define ID_TOOLS_BILIBILI               32788
#define ID_TOOLS_STUDY                  32789
#define ID_TOOLS_DOWNLOAD               32790
#define ID_TOOLS_POWERSHELL             32791
#define ID_TOOLS_WSL                    32792
#define ID_TOOLS_GITBASH                32793
#define ID_WINDOW_LOCATE                32794
#define ID_WINDOW_UNTOPMOST             32795
#define ID_WINDOW_CLOSE                 32796
#define ID_HELP_SHORTCUTS               32797
#define ID_HELP_GITHUB                  32798
#define ID_TOOLS_QRCODE                 32811
#define ID_TOOLS_SCREENSHOT_OCR         32812
#define ID_TOOLS_BATCH_RENAME           32813
#define ID_HELP_REGEX_GUIDE             32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
